name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CFLAGS: -Werror

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl1-mesa-dev
    - name: build
      run: mkdir build && cd build && cmake .. && make
    - name: cpp-style
      run: clang-format --dry-run --Werror src/*.cpp
    - name: h-style
      run: clang-format --dry-run --Werror include/*.h
    
